enum GameActionTypes {
  CLEAR_REDUCER = 'game/CLEAR_REDUCER',
  SET_LAST_ACTION_GAME = 'game/SET_LAST_ACTION_GAME',
  SET_DROPZONES = 'game/SET_DROPZONES',
  SET_FINISH_EXERCISE = 'game/SET_FINISH_EXERCISE',
  SET_SCORE = 'game/SET_SCORE',
  SET_USER_NAME = 'game/SET_USER_NAME',
}

export default GameActionTypes;
